version: "3.9"
services:
  kustosz:
    dns:
      - 192.168.4.200
      - 192.168.4.201
      - 192.168.4.203
      - 192.168.4.204
    environment:
      - RABBITMQ_ERLANG_COOKIE=UGH
    build:
      args:
        ALPINE_VERSION: "latest"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "rabbitmq:dev"
    image: "rabbitmq:dev"
    hostname: "rabbitmq"
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/kustosz/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/kustosz/backup-volume
      
