#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

APP_NAME="kustosz"
DB_PATH="/mnt/volumes/container/db.sqlite3"

app_version() {
 # /sbin/apk list --installed --no-cache | /bin/grep "$APP_NAME" | /usr/bin/awk -F ' ' '{print $1}' | /usr/bin/awk -F '-' '{print $3}'
 echo "1.0.0"
}

export ENV_FOR_DYNACONF="production"
export DJANGO_SETTINGS_MODULE=kustosz.settings
export KUSTOSZ_BASE_DIR="/home/kustosz/"

/usr/bin/sudo /usr/sbin/nginx
/usr/bin/gunicorn kustosz.wsgi --bind 0.0.0.0:8888 > /mnt/volumes/container/.log 2>&1 &
/bin/sleep 5

if [ ! -f  $DB_PATH ] ; then
 /usr/bin/kustosz-manager migrate
 /usr/bin/kustosz-manager createcachetable
fi

# /usr/bin/celery -A kustosz worker -l INFO -Q celery > /dev/stdout 2>&1 &
# /usr/bin/celery -A kustosz worker -l INFO -Q feed_fetcher --concurrency 1 > /dev/stdout 2>&1 &

log "-i" "entrypoint" "Launch Application - $APP_NAME($(app_version))"
if [ -z "$@" ] ; then
 # /usr/bin/gunicorn kustosz.wsgi --bind 0.0.0.0:8888
 /usr/bin/celery -A kustosz worker -l INFO -Q feed_fetcher,celery
 return 1
else
 echo "/usr/bin/gunicorn kustosz.wsgi --bind 0.0.0.0:8888" > /home/kustosz/.ash_history
 echo "kustosz-manager createsuperuser --email {email} --username {username}" > /home/kustosz/.ash_history
 log "-i" "entrypoint" "Launch Application [BACKGROUND]"
 # /usr/sbin/rabbitmq-server -detached
 # /usr/bin/gunicorn kustosz.wsgi --bind 0.0.0.0:8888 >> /mnt/volumes/container/.log 2>&1 &
 /usr/bin/celery -A kustosz worker -l INFO -Q feed_fetcher,celery >> /mnt/volumes/container/.log 2>&1 &
 return 0
fi
